[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.1"

# Lists people or organizations that are considered the "authors" of the package.
authors = [
    "Author Name <author_name@example.com>",
]

# The title and description fields are primarily for displaying extension info in the UI
title = 'Usd Search Window'
description = "A simple USD Search UI example. Use it as a starting point for your extensions."

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/Overview.md"

# Path (relative to the root) of changelog
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# URL of the extension source repository.
# repository = "https://github.com/example/repository_name"

# One of categories for the UI.
category = "Sample"

# Keywords for the extension
keywords = ["usd", "search", "sample"]

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extension manager. It is recommended to be square, of size 256x256.
# icon = "data/icon.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main module, it is publicly available as: import omni.kit.window.usd_search
[[python.module]]
name = "omni.kit.window.usd_search"

[settings.exts."omni.kit.window.usd_search"]
# This is the server for USD Search API
host_url = "https://ai.api.nvidia.com/v1/omniverse/nvidia/usdsearch"

# Alternative to NVIDIA_API_KEY environment variable
nvidia_api_key = "" # < Put API Key Here ( takes precedent )

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test"  # UI testing extension
]

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]